"""Turn this template into a project: rename the package everywhere, once.

GitHub's "Use this template" copies files; it substitutes nothing. Without this
script the first hour of every new project is renaming `agent_template` by hand
across `pyproject.toml`, the source tree, the tests and the agent instructions —
which is exactly the friction the template exists to remove.

Run it through the Makefile so the lockfile is refreshed in the same breath:

    make rename NAME=my-project

It rewrites the placeholder in three spellings (distribution, module, class
prefix), renames the package directory, swaps in the project README, removes
every template-only artefact — including itself — and re-runs the formatter,
because a textual rename can leave imports out of order and an unformatted tree
fails CI.

CI runs this against the tree and then runs the full gate on the result, so
"the template works" is a check that fails, not a claim in a README.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SELF = Path(__file__).resolve()

DIST_PLACEHOLDER = "agent-template"
MODULE_PLACEHOLDER = "agent_template"
CLASS_PLACEHOLDER = "AgentTemplate"

# Directories that hold no project source.
SKIP_DIRS = {
    ".git",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "dist",
    "build",
}
# uv.lock is regenerated by `uv lock`; this script is excluded so its own
# placeholder constants survive long enough to be used.
SKIP_FILES = {"uv.lock", SELF.name}
TEXT_SUFFIXES = {".py", ".toml", ".md", ".yml", ".yaml", ".cfg", ".txt", ".example", ""}

# The Makefile block that only makes sense while this is still a template.
MAKEFILE_BLOCK = re.compile(
    r"\n# >>> template-only.*?# <<< template-only\n",
    re.DOTALL,
)

VALID_NAME = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$")


def to_module(dist_name: str) -> str:
    """`my-project` -> `my_project`. Distribution names use hyphens; imports cannot."""
    return dist_name.replace("-", "_")


def to_class_prefix(module_name: str) -> str:
    """`my_project` -> `MyProject`, for the root exception class."""
    return "".join(part.capitalize() for part in module_name.split("_"))


def iter_text_files(root: Path) -> list[Path]:
    found: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.is_symlink():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.name in SKIP_FILES or path.suffix not in TEXT_SUFFIXES:
            continue
        found.append(path)
    return found


def rewrite(paths: list[Path], dist: str, module: str, class_prefix: str) -> int:
    """Replace the three placeholder spellings. Returns the number of files changed."""
    changed = 0
    for path in paths:
        try:
            before = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:  # a binary file with a text-ish suffix
            continue
        after = (
            before.replace(CLASS_PLACEHOLDER, class_prefix)
            .replace(MODULE_PLACEHOLDER, module)
            .replace(DIST_PLACEHOLDER, dist)
        )
        if after != before:
            path.write_text(after, encoding="utf-8")
            changed += 1
    return changed


def strip_template_only(root: Path) -> None:
    """Remove the artefacts that exist only to serve the template itself."""
    (root / ".github" / "workflows" / "template.yml").unlink(missing_ok=True)

    makefile = root / "Makefile"
    if makefile.is_file():
        text = makefile.read_text(encoding="utf-8")
        text = MAKEFILE_BLOCK.sub("\n", text)
        text = text.replace(" rename clean", " clean")
        makefile.write_text(text, encoding="utf-8")

    # This script is the only thing in scripts/, and mypy treats a configured
    # directory with no .py files in it as an error rather than as empty.
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        text = pyproject.read_text(encoding="utf-8")
        text = text.replace('["src", "tests", "scripts"]', '["src", "tests"]')
        pyproject.write_text(text, encoding="utf-8")


def reformat(root: Path) -> bool:
    """Re-sort and re-format. A rename reorders symbols; ruff decides the order."""
    ruff = shutil.which("ruff")
    if ruff is None:
        return False
    subprocess.run([ruff, "check", "--fix", "--quiet", "."], cwd=root, check=False)
    subprocess.run([ruff, "format", "--quiet", "."], cwd=root, check=False)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rename this template into a project.")
    parser.add_argument("--name", required=True, help="distribution name, e.g. my-project")
    parser.add_argument("--root", type=Path, default=ROOT, help="tree to rewrite")
    args = parser.parse_args(argv)

    dist: str = args.name
    root: Path = args.root.resolve()

    if not VALID_NAME.match(dist):
        print(
            f"'{dist}' is not a usable distribution name: lowercase letters, "
            "digits and single hyphens, starting with a letter.",
            file=sys.stderr,
        )
        return 2

    module = to_module(dist)
    package = root / "src" / MODULE_PLACEHOLDER
    if not package.is_dir():
        print(f"No package at {package} — has this template already been renamed?", file=sys.stderr)
        return 1

    changed = rewrite(iter_text_files(root), dist, module, to_class_prefix(module))
    package.rename(root / "src" / module)

    # The template's own README explains the layout; a project needs its own.
    stub = root / "README.project.md"
    if stub.is_file():
        shutil.move(str(stub), str(root / "README.md"))

    strip_template_only(root)
    formatted = reformat(root)

    print(f"Renamed to '{dist}' (module '{module}') across {changed} files.")
    if not formatted:
        print("ruff was not on PATH — run `make format` before committing.", file=sys.stderr)
    print("Next: fill in README.md, then set description/keywords/authors in pyproject.toml.")

    SELF.unlink(missing_ok=True)  # nothing left for this script to do
    if SELF.parent.is_dir() and not any(SELF.parent.iterdir()):
        SELF.parent.rmdir()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
